-- DEV SEED DATA — demo rows so the admin console has something to show
-- while previewing locally. Safe to delete at any time (see the cleanup
-- block at the bottom of this file). This is NOT a migration: it is not
-- applied by `supabase db push` and must be run manually (SQL Editor or
-- `supabase db execute -f supabase/seed.sql`) against whichever project
-- you intend to seed. Do not run this against a real production project
-- once one exists.

INSERT INTO asset_categories (name, tag_prefix, is_depreciable, default_useful_life_months, is_physical)
VALUES
  ('Laptop', 'LT', true, 36, true),
  ('Monitor', 'MN', true, 60, true),
  ('Office Chair', 'CH', true, 84, true)
ON CONFLICT (tag_prefix) DO NOTHING;

INSERT INTO locations (name, type)
VALUES
  ('Executive Room', 'room'),
  ('HR Room', 'room'),
  ('Dev Lounge', 'room'),
  ('Engineering Room', 'room'),
  ('Sales Room', 'room'),
  ('Marketing Room', 'room'),
  ('AI Automation Room', 'room')
ON CONFLICT DO NOTHING;

-- asset_tag / public_slug are generated by trig_asset_before_insert(), so
-- only category_id / location_id / descriptive fields need values here.
INSERT INTO assets (category_id, make, model, serial_no, condition, status, location_id, notes)
SELECT c.id, v.make, v.model, v.serial_no, v.condition::asset_condition, v.status::asset_status, l.id, '[DEV SEED] demo asset'
FROM (VALUES
  ('Laptop',       'Dell',    'Latitude 5440', 'SN-LT-001', 'good', 'assigned',  'Engineering Room'),
  ('Laptop',       'Apple',   'MacBook Pro 14','SN-LT-002', 'new',  'in_stock',  'Dev Lounge'),
  ('Monitor',      'LG',      '27UL850',       'SN-MN-001', 'good', 'assigned',  'Engineering Room'),
  ('Monitor',      'Dell',    'P2419H',        'SN-MN-002', 'fair', 'in_repair', 'AI Automation Room'),
  ('Office Chair', 'Herman',  'Aeron',         'SN-CH-001', 'good', 'assigned',  'Executive Room'),
  ('Office Chair', 'Steelcase','Leap',         'SN-CH-002', 'poor', 'in_stock',  'HR Room')
) AS v(category_name, make, model, serial_no, condition, status, location_name)
JOIN asset_categories c ON c.name = v.category_name
JOIN locations l ON l.name = v.location_name
WHERE NOT EXISTS (SELECT 1 FROM assets a WHERE a.serial_no = v.serial_no);

-- --- Cleanup: run this block manually to remove only the demo rows above ---
-- DELETE FROM assets WHERE notes = '[DEV SEED] demo asset';
-- DELETE FROM locations WHERE name IN ('Executive Room', 'HR Room', 'Dev Lounge', 'Engineering Room', 'Sales Room', 'Marketing Room', 'AI Automation Room');
-- DELETE FROM asset_categories WHERE tag_prefix IN ('LT', 'MN', 'CH');
